# Generated by Django 6.1.1 on 2026-09-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(default=499),
        ),
    ]
